[colors.primary]
background = "#24283b"

[font]
size = 18.0

[font.normal]
family = "FiraCode Nerd Font"

[shell]
program = "nu"

[keyboard]
bindings = [{ key = "Slash", mods = "Control", "chars" = "\u001F" }]

[window]
dynamic_title = false
