theme = "zaucy"

[editor]
line-number = "relative"
default-line-ending = "lf"

[editor.cursor-shape]
normal = "block"
insert= "bar"
select = "underline"

[editor.whitespace.render]
space = "none"
tab = "all"
newline = "none"

[editor.indent-guides]
render = true


[editor.statusline]
left = ["mode", "spinner", "spacer", "version-control"]
center = ["file-modification-indicator", "file-base-name", "diagnostics"]
right = ["position", "file-line-ending"]
separator = "│"
mode.normal = "⌬"
mode.insert = "✎"
mode.select = "⌨"

[keys.normal]
# Move lines up and down
A-j    = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-down = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-k    = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
A-up   = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
